swagger: "2.0"
info:
  title: proto/v1/service.proto
  version: version not set
tags:
  - name: CoreService
consumes:
  - application/json
produces:
  - application/json
paths:
  /activities:
    get:
      summary: Get activity
      operationId: CoreService_ListActivity
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1ListActivityResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
        - name: offset
          in: query
          required: false
          type: integer
          format: int32
      tags:
        - activity
  /activity:
    post:
      summary: Create activity
      operationId: CoreService_CreateActivity
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Activity'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1CreateActivityRequest'
      tags:
        - activity
  /activity/{sku}:
    get:
      summary: Get activity
      description: Returns the activity
      operationId: CoreService_GetActivity
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1Activity'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: sku
          in: path
          required: true
          type: string
      tags:
        - activity
    delete:
      summary: Delete activity
      operationId: CoreService_DeleteActivity
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: sku
          in: path
          required: true
          type: string
      tags:
        - activity
  /activity/order/{order_id}:
    get:
      summary: Get activity
      description: Returns the activity
      operationId: CoreService_GetActivityByOrderID
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetActivityByOrderIDResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: order_id
          in: path
          required: true
          type: string
        - name: language
          in: query
          required: false
          type: string
      tags:
        - activity
  /gpx/{sku}/download:
    get:
      summary: Get gpx
      description: Returns the gpx
      operationId: CoreService_DownloadGPX
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DownloadGPXResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: sku
          in: path
          required: true
          type: string
      tags:
        - gpx
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1Activity:
    type: object
    properties:
      sku:
        type: string
      gpx:
        type: string
      product_id:
        type: string
      names:
        type: object
        additionalProperties:
          type: string
      descriptions:
        type: object
        additionalProperties:
          type: string
      image:
        type: string
      transports:
        type: object
        additionalProperties:
          type: string
      supplier:
        $ref: '#/definitions/v1Supplier'
      extra_meeting_info:
        type: object
        additionalProperties:
          type: string
  v1CreateActivityRequest:
    type: object
    properties:
      sku:
        type: string
      gpx:
        type: string
      product_id:
        type: string
      names:
        type: object
        additionalProperties:
          type: string
      descriptions:
        type: object
        additionalProperties:
          type: string
      image:
        type: string
      transports:
        type: object
        additionalProperties:
          type: string
      supplier:
        $ref: '#/definitions/v1Supplier'
      extra_meeting_info:
        type: object
        additionalProperties:
          type: string
  v1DownloadGPXResponse:
    type: object
    properties:
      gpx:
        type: string
  v1GetActivityByOrderIDResponse:
    type: object
    properties:
      order_id:
        type: string
      product_id:
        type: string
      name:
        type: string
      sku:
        type: string
      short_description:
        type: string
      geo_lat:
        type: string
      geo_lon:
        type: string
      distance:
        type: string
      location_address:
        type: string
      city:
        type: string
      zipcode:
        type: string
      city_id:
        type: string
      region_id:
        type: string
      poi_ids:
        type: string
      country_id:
        type: string
      thumbnail:
        type: string
      image:
        type: string
      image_label:
        type: string
      rating_summary:
        type: string
      reviews_count:
        type: string
      Description:
        type: string
      date:
        type: string
      purchased_at:
        type: string
      resources:
        type: array
        items:
          type: string
      details:
        $ref: '#/definitions/v1Activity'
  v1ListActivityResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1Activity'
      total:
        type: integer
        format: int32
  v1Supplier:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      phone:
        type: string
      address:
        type: string
      city:
        type: string
      zipcode:
        type: string
      country:
        type: string
