swagger: "2.0"
info:
  title: proto/v1/service.proto
  version: version not set
tags:
  - name: CoreService
consumes:
  - application/json
produces:
  - application/json
paths:
  /activity/{order_id}:
    get:
      summary: Get activity
      description: Returns the activity
      operationId: CoreService_GetActivity
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1GetActivityResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: order_id
          in: path
          required: true
          type: string
        - name: language
          in: query
          required: false
          type: string
      tags:
        - activity
  /gpx/{sku}:
    get:
      summary: Get gpx
      description: Returns the gpx
      operationId: CoreService_DownloadGPX
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1DownloadGPXResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: sku
          in: path
          required: true
          type: string
      tags:
        - gpx
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v1DownloadGPXResponse:
    type: object
    properties:
      gpx:
        type: string
  v1GPX:
    type: object
    properties:
      sku:
        type: string
      gpx:
        type: string
  v1GetActivityResponse:
    type: object
    properties:
      order_id:
        type: string
      product_id:
        type: string
      name:
        type: string
      sku:
        type: string
      short_description:
        type: string
      geo_lat:
        type: string
      geo_lon:
        type: string
      distance:
        type: string
      location_address:
        type: string
      city:
        type: string
      zipcode:
        type: string
      city_id:
        type: string
      region_id:
        type: string
      poi_ids:
        type: string
      country_id:
        type: string
      thumbnail:
        type: string
      image:
        type: string
      image_label:
        type: string
      rating_summary:
        type: string
      reviews_count:
        type: string
      Description:
        type: string
  v1ListGPXResponse:
    type: object
    properties:
      items:
        type: array
        items:
          type: object
          $ref: '#/definitions/v1GPX'
      total:
        type: integer
        format: int32
