mongo:
  host: "127.0.0.1"
  port: 27017
  user: "root"
  password: "root"
regiondo:
  debug: true
  url: "https://api.regiondo.com/v1"
  timeout: 30s
  publicKey: ""
  privateKey: ""
server:
  http:
    addr: ":5000"
  grpc:
    addr: ":8000"
  public: false
